### ISSUE TITLE
Simpy does not work

### ISSUE THREAD

**Issue by kimmymonassar** [wiamsuri/nuxt-nginx-docker#6]
I've cloned the repo and did everything correct but nginx does not serve my website at port 80 even though it should proxy the nuxt server thats working properly at localhost:3000

**Comment by wiamsuri** [comment]
What is the environment you are working with? Windows Server, Ubuntu? Usually, runnning port number lower than 1024 (including port 80 for nginx) will require user to have more priviledge than usual. [https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html]

I'm not sure if user permission is the case here or not. If you can provide more information, maybe I can help.

**Comment by kimmymonassar** [comment]
My bad, my Nginx config had to be configured properly, took me a few days to find but at last I did it 😬
